// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/confmap"

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms, confmap.WithErrorUnused())
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for mongodb metrics.
type MetricsConfig struct {
	MongodbCacheOperations        MetricConfig `mapstructure:"mongodb.cache.operations"`
	MongodbCollectionCount        MetricConfig `mapstructure:"mongodb.collection.count"`
	MongodbConnectionCount        MetricConfig `mapstructure:"mongodb.connection.count"`
	MongodbCursorCount            MetricConfig `mapstructure:"mongodb.cursor.count"`
	MongodbCursorTimeoutCount     MetricConfig `mapstructure:"mongodb.cursor.timeout.count"`
	MongodbDataSize               MetricConfig `mapstructure:"mongodb.data.size"`
	MongodbDatabaseCount          MetricConfig `mapstructure:"mongodb.database.count"`
	MongodbDocumentOperationCount MetricConfig `mapstructure:"mongodb.document.operation.count"`
	MongodbExtentCount            MetricConfig `mapstructure:"mongodb.extent.count"`
	MongodbGlobalLockTime         MetricConfig `mapstructure:"mongodb.global_lock.time"`
	MongodbHealth                 MetricConfig `mapstructure:"mongodb.health"`
	MongodbIndexAccessCount       MetricConfig `mapstructure:"mongodb.index.access.count"`
	MongodbIndexCount             MetricConfig `mapstructure:"mongodb.index.count"`
	MongodbIndexSize              MetricConfig `mapstructure:"mongodb.index.size"`
	MongodbLockAcquireCount       MetricConfig `mapstructure:"mongodb.lock.acquire.count"`
	MongodbLockAcquireTime        MetricConfig `mapstructure:"mongodb.lock.acquire.time"`
	MongodbLockAcquireWaitCount   MetricConfig `mapstructure:"mongodb.lock.acquire.wait_count"`
	MongodbLockDeadlockCount      MetricConfig `mapstructure:"mongodb.lock.deadlock.count"`
	MongodbMemoryUsage            MetricConfig `mapstructure:"mongodb.memory.usage"`
	MongodbNetworkIoReceive       MetricConfig `mapstructure:"mongodb.network.io.receive"`
	MongodbNetworkIoTransmit      MetricConfig `mapstructure:"mongodb.network.io.transmit"`
	MongodbNetworkRequestCount    MetricConfig `mapstructure:"mongodb.network.request.count"`
	MongodbObjectCount            MetricConfig `mapstructure:"mongodb.object.count"`
	MongodbOperationCount         MetricConfig `mapstructure:"mongodb.operation.count"`
	MongodbOperationLatencyTime   MetricConfig `mapstructure:"mongodb.operation.latency.time"`
	MongodbOperationReplCount     MetricConfig `mapstructure:"mongodb.operation.repl.count"`
	MongodbOperationTime          MetricConfig `mapstructure:"mongodb.operation.time"`
	MongodbSessionCount           MetricConfig `mapstructure:"mongodb.session.count"`
	MongodbStorageSize            MetricConfig `mapstructure:"mongodb.storage.size"`
	MongodbUptime                 MetricConfig `mapstructure:"mongodb.uptime"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		MongodbCacheOperations: MetricConfig{
			Enabled: false,
		},
		MongodbCollectionCount: MetricConfig{
			Enabled: false,
		},
		MongodbConnectionCount: MetricConfig{
			Enabled: false,
		},
		MongodbCursorCount: MetricConfig{
			Enabled: false,
		},
		MongodbCursorTimeoutCount: MetricConfig{
			Enabled: false,
		},
		MongodbDataSize: MetricConfig{
			Enabled: false,
		},
		MongodbDatabaseCount: MetricConfig{
			Enabled: false,
		},
		MongodbDocumentOperationCount: MetricConfig{
			Enabled: false,
		},
		MongodbExtentCount: MetricConfig{
			Enabled: false,
		},
		MongodbGlobalLockTime: MetricConfig{
			Enabled: false,
		},
		MongodbHealth: MetricConfig{
			Enabled: false,
		},
		MongodbIndexAccessCount: MetricConfig{
			Enabled: false,
		},
		MongodbIndexCount: MetricConfig{
			Enabled: false,
		},
		MongodbIndexSize: MetricConfig{
			Enabled: false,
		},
		MongodbLockAcquireCount: MetricConfig{
			Enabled: false,
		},
		MongodbLockAcquireTime: MetricConfig{
			Enabled: false,
		},
		MongodbLockAcquireWaitCount: MetricConfig{
			Enabled: false,
		},
		MongodbLockDeadlockCount: MetricConfig{
			Enabled: false,
		},
		MongodbMemoryUsage: MetricConfig{
			Enabled: false,
		},
		MongodbNetworkIoReceive: MetricConfig{
			Enabled: false,
		},
		MongodbNetworkIoTransmit: MetricConfig{
			Enabled: false,
		},
		MongodbNetworkRequestCount: MetricConfig{
			Enabled: false,
		},
		MongodbObjectCount: MetricConfig{
			Enabled: false,
		},
		MongodbOperationCount: MetricConfig{
			Enabled: true,
		},
		MongodbOperationLatencyTime: MetricConfig{
			Enabled: true,
		},
		MongodbOperationReplCount: MetricConfig{
			Enabled: false,
		},
		MongodbOperationTime: MetricConfig{
			Enabled: true,
		},
		MongodbSessionCount: MetricConfig{
			Enabled: false,
		},
		MongodbStorageSize: MetricConfig{
			Enabled: false,
		},
		MongodbUptime: MetricConfig{
			Enabled: false,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
}

// ResourceAttributesConfig provides config for mongodb resource attributes.
type ResourceAttributesConfig struct {
	Database            ResourceAttributeConfig `mapstructure:"database"`
	MongodbDatabaseName ResourceAttributeConfig `mapstructure:"mongodb.database.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		Database: ResourceAttributeConfig{
			Enabled: false,
		},
		MongodbDatabaseName: ResourceAttributeConfig{
			Enabled: false,
		},
	}
}

// MetricsBuilderConfig is a configuration for mongodb metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
