// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/confmap"

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms, confmap.WithErrorUnused())
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for postgresql metrics.
type MetricsConfig struct {
	PostgresqlBackends                 MetricConfig `mapstructure:"postgresql.backends"`
	PostgresqlBgwriterBuffersAllocated MetricConfig `mapstructure:"postgresql.bgwriter.buffers.allocated"`
	PostgresqlBgwriterBuffersWrites    MetricConfig `mapstructure:"postgresql.bgwriter.buffers.writes"`
	PostgresqlBgwriterCheckpointCount  MetricConfig `mapstructure:"postgresql.bgwriter.checkpoint.count"`
	PostgresqlBgwriterDuration         MetricConfig `mapstructure:"postgresql.bgwriter.duration"`
	PostgresqlBgwriterMaxwritten       MetricConfig `mapstructure:"postgresql.bgwriter.maxwritten"`
	PostgresqlBlocksRead               MetricConfig `mapstructure:"postgresql.blocks_read"`
	PostgresqlCommits                  MetricConfig `mapstructure:"postgresql.commits"`
	PostgresqlConnectionCount          MetricConfig `mapstructure:"postgresql.connection.count"`
	PostgresqlConnectionMax            MetricConfig `mapstructure:"postgresql.connection.max"`
	PostgresqlDatabaseCount            MetricConfig `mapstructure:"postgresql.database.count"`
	PostgresqlDbSize                   MetricConfig `mapstructure:"postgresql.db_size"`
	PostgresqlDeadlocks                MetricConfig `mapstructure:"postgresql.deadlocks"`
	PostgresqlIndexScans               MetricConfig `mapstructure:"postgresql.index.scans"`
	PostgresqlIndexSize                MetricConfig `mapstructure:"postgresql.index.size"`
	PostgresqlOperations               MetricConfig `mapstructure:"postgresql.operations"`
	PostgresqlReplicationDataDelay     MetricConfig `mapstructure:"postgresql.replication.data_delay"`
	PostgresqlRollbacks                MetricConfig `mapstructure:"postgresql.rollbacks"`
	PostgresqlRows                     MetricConfig `mapstructure:"postgresql.rows"`
	PostgresqlSequentialScans          MetricConfig `mapstructure:"postgresql.sequential_scans"`
	PostgresqlTableCount               MetricConfig `mapstructure:"postgresql.table.count"`
	PostgresqlTableSize                MetricConfig `mapstructure:"postgresql.table.size"`
	PostgresqlTableVacuumCount         MetricConfig `mapstructure:"postgresql.table.vacuum.count"`
	PostgresqlTempFiles                MetricConfig `mapstructure:"postgresql.temp_files"`
	PostgresqlWalAge                   MetricConfig `mapstructure:"postgresql.wal.age"`
	PostgresqlWalLag                   MetricConfig `mapstructure:"postgresql.wal.lag"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PostgresqlBackends: MetricConfig{
			Enabled: false,
		},
		PostgresqlBgwriterBuffersAllocated: MetricConfig{
			Enabled: false,
		},
		PostgresqlBgwriterBuffersWrites: MetricConfig{
			Enabled: false,
		},
		PostgresqlBgwriterCheckpointCount: MetricConfig{
			Enabled: false,
		},
		PostgresqlBgwriterDuration: MetricConfig{
			Enabled: false,
		},
		PostgresqlBgwriterMaxwritten: MetricConfig{
			Enabled: false,
		},
		PostgresqlBlocksRead: MetricConfig{
			Enabled: false,
		},
		PostgresqlCommits: MetricConfig{
			Enabled: false,
		},
		PostgresqlConnectionCount: MetricConfig{
			Enabled: true,
		},
		PostgresqlConnectionMax: MetricConfig{
			Enabled: false,
		},
		PostgresqlDatabaseCount: MetricConfig{
			Enabled: false,
		},
		PostgresqlDbSize: MetricConfig{
			Enabled: false,
		},
		PostgresqlDeadlocks: MetricConfig{
			Enabled: false,
		},
		PostgresqlIndexScans: MetricConfig{
			Enabled: false,
		},
		PostgresqlIndexSize: MetricConfig{
			Enabled: false,
		},
		PostgresqlOperations: MetricConfig{
			Enabled: false,
		},
		PostgresqlReplicationDataDelay: MetricConfig{
			Enabled: false,
		},
		PostgresqlRollbacks: MetricConfig{
			Enabled: false,
		},
		PostgresqlRows: MetricConfig{
			Enabled: false,
		},
		PostgresqlSequentialScans: MetricConfig{
			Enabled: false,
		},
		PostgresqlTableCount: MetricConfig{
			Enabled: false,
		},
		PostgresqlTableSize: MetricConfig{
			Enabled: false,
		},
		PostgresqlTableVacuumCount: MetricConfig{
			Enabled: false,
		},
		PostgresqlTempFiles: MetricConfig{
			Enabled: false,
		},
		PostgresqlWalAge: MetricConfig{
			Enabled: false,
		},
		PostgresqlWalLag: MetricConfig{
			Enabled: false,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
}

// ResourceAttributesConfig provides config for postgresql resource attributes.
type ResourceAttributesConfig struct {
	PostgresqlDatabaseName ResourceAttributeConfig `mapstructure:"postgresql.database.name"`
	PostgresqlIndexName    ResourceAttributeConfig `mapstructure:"postgresql.index.name"`
	PostgresqlTableName    ResourceAttributeConfig `mapstructure:"postgresql.table.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		PostgresqlDatabaseName: ResourceAttributeConfig{
			Enabled: true,
		},
		PostgresqlIndexName: ResourceAttributeConfig{
			Enabled: false,
		},
		PostgresqlTableName: ResourceAttributeConfig{
			Enabled: false,
		},
	}
}

// MetricsBuilderConfig is a configuration for postgresql metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
