// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for postgresql metrics.
type MetricsConfig struct {
	PostgresqlAnalyzed                 MetricConfig `mapstructure:"postgresql.analyzed"`
	PostgresqlAutoanalyzed             MetricConfig `mapstructure:"postgresql.autoanalyzed"`
	PostgresqlAutovacuumed             MetricConfig `mapstructure:"postgresql.autovacuumed"`
	PostgresqlBackends                 MetricConfig `mapstructure:"postgresql.backends"`
	PostgresqlBgwriterBuffersAllocated MetricConfig `mapstructure:"postgresql.bgwriter.buffers.allocated"`
	PostgresqlBgwriterBuffersWrites    MetricConfig `mapstructure:"postgresql.bgwriter.buffers.writes"`
	PostgresqlBgwriterCheckpointCount  MetricConfig `mapstructure:"postgresql.bgwriter.checkpoint.count"`
	PostgresqlBgwriterDuration         MetricConfig `mapstructure:"postgresql.bgwriter.duration"`
	PostgresqlBgwriterMaxwritten       MetricConfig `mapstructure:"postgresql.bgwriter.maxwritten"`
	PostgresqlBlkReadTime              MetricConfig `mapstructure:"postgresql.blk_read_time"`
	PostgresqlBlkWriteTime             MetricConfig `mapstructure:"postgresql.blk_write_time"`
	PostgresqlBlksHit                  MetricConfig `mapstructure:"postgresql.blks_hit"`
	PostgresqlBlksRead                 MetricConfig `mapstructure:"postgresql.blks_read"`
	PostgresqlBlocksRead               MetricConfig `mapstructure:"postgresql.blocks_read"`
	PostgresqlBufferHit                MetricConfig `mapstructure:"postgresql.buffer_hit"`
	PostgresqlCommits                  MetricConfig `mapstructure:"postgresql.commits"`
	PostgresqlConnectionCount          MetricConfig `mapstructure:"postgresql.connection.count"`
	PostgresqlConnectionMax            MetricConfig `mapstructure:"postgresql.connection.max"`
	PostgresqlDatabaseCount            MetricConfig `mapstructure:"postgresql.database.count"`
	PostgresqlDatabaseLocks            MetricConfig `mapstructure:"postgresql.database.locks"`
	PostgresqlDbSize                   MetricConfig `mapstructure:"postgresql.db_size"`
	PostgresqlDeadlocks                MetricConfig `mapstructure:"postgresql.deadlocks"`
	PostgresqlFunctionCalls            MetricConfig `mapstructure:"postgresql.function.calls"`
	PostgresqlIndexBlocksRead          MetricConfig `mapstructure:"postgresql.index.blocks_read"`
	PostgresqlIndexRowsRead            MetricConfig `mapstructure:"postgresql.index.rows_read"`
	PostgresqlIndexScans               MetricConfig `mapstructure:"postgresql.index.scans"`
	PostgresqlIndexSize                MetricConfig `mapstructure:"postgresql.index.size"`
	PostgresqlIndexBloat               MetricConfig `mapstructure:"postgresql.index_bloat"`
	PostgresqlLiveRows                 MetricConfig `mapstructure:"postgresql.live_rows"`
	PostgresqlOperations               MetricConfig `mapstructure:"postgresql.operations"`
	PostgresqlQueryCount               MetricConfig `mapstructure:"postgresql.query.count"`
	PostgresqlQueryTotalExecTime       MetricConfig `mapstructure:"postgresql.query.total_exec_time"`
	PostgresqlReplicationDataDelay     MetricConfig `mapstructure:"postgresql.replication.data_delay"`
	PostgresqlRollbacks                MetricConfig `mapstructure:"postgresql.rollbacks"`
	PostgresqlRows                     MetricConfig `mapstructure:"postgresql.rows"`
	PostgresqlRowsDeleted              MetricConfig `mapstructure:"postgresql.rows_deleted"`
	PostgresqlRowsFetched              MetricConfig `mapstructure:"postgresql.rows_fetched"`
	PostgresqlRowsInserted             MetricConfig `mapstructure:"postgresql.rows_inserted"`
	PostgresqlRowsUpdated              MetricConfig `mapstructure:"postgresql.rows_updated"`
	PostgresqlSequentialScans          MetricConfig `mapstructure:"postgresql.sequential_scans"`
	PostgresqlTableCount               MetricConfig `mapstructure:"postgresql.table.count"`
	PostgresqlTableSize                MetricConfig `mapstructure:"postgresql.table.size"`
	PostgresqlTableVacuumCount         MetricConfig `mapstructure:"postgresql.table.vacuum.count"`
	PostgresqlTableBloat               MetricConfig `mapstructure:"postgresql.table_bloat"`
	PostgresqlTempIo                   MetricConfig `mapstructure:"postgresql.temp.io"`
	PostgresqlTempFiles                MetricConfig `mapstructure:"postgresql.temp_files"`
	PostgresqlToastBlocksHit           MetricConfig `mapstructure:"postgresql.toast.blocks_hit"`
	PostgresqlToastIndexBlocksRead     MetricConfig `mapstructure:"postgresql.toast.index.blocks_read"`
	PostgresqlToastSize                MetricConfig `mapstructure:"postgresql.toast.size"`
	PostgresqlTransactionsDurationMax  MetricConfig `mapstructure:"postgresql.transactions.duration.max"`
	PostgresqlTransactionsDurationSum  MetricConfig `mapstructure:"postgresql.transactions.duration.sum"`
	PostgresqlTupDeleted               MetricConfig `mapstructure:"postgresql.tup_deleted"`
	PostgresqlTupFetched               MetricConfig `mapstructure:"postgresql.tup_fetched"`
	PostgresqlTupInserted              MetricConfig `mapstructure:"postgresql.tup_inserted"`
	PostgresqlTupReturned              MetricConfig `mapstructure:"postgresql.tup_returned"`
	PostgresqlTupUpdated               MetricConfig `mapstructure:"postgresql.tup_updated"`
	PostgresqlWalAge                   MetricConfig `mapstructure:"postgresql.wal.age"`
	PostgresqlWalCount                 MetricConfig `mapstructure:"postgresql.wal.count"`
	PostgresqlWalDelay                 MetricConfig `mapstructure:"postgresql.wal.delay"`
	PostgresqlWalLag                   MetricConfig `mapstructure:"postgresql.wal.lag"`
	PostgresqlWalSize                  MetricConfig `mapstructure:"postgresql.wal.size"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PostgresqlAnalyzed: MetricConfig{
			Enabled: true,
		},
		PostgresqlAutoanalyzed: MetricConfig{
			Enabled: true,
		},
		PostgresqlAutovacuumed: MetricConfig{
			Enabled: true,
		},
		PostgresqlBackends: MetricConfig{
			Enabled: true,
		},
		PostgresqlBgwriterBuffersAllocated: MetricConfig{
			Enabled: true,
		},
		PostgresqlBgwriterBuffersWrites: MetricConfig{
			Enabled: true,
		},
		PostgresqlBgwriterCheckpointCount: MetricConfig{
			Enabled: true,
		},
		PostgresqlBgwriterDuration: MetricConfig{
			Enabled: true,
		},
		PostgresqlBgwriterMaxwritten: MetricConfig{
			Enabled: true,
		},
		PostgresqlBlkReadTime: MetricConfig{
			Enabled: false,
		},
		PostgresqlBlkWriteTime: MetricConfig{
			Enabled: false,
		},
		PostgresqlBlksHit: MetricConfig{
			Enabled: false,
		},
		PostgresqlBlksRead: MetricConfig{
			Enabled: false,
		},
		PostgresqlBlocksRead: MetricConfig{
			Enabled: true,
		},
		PostgresqlBufferHit: MetricConfig{
			Enabled: true,
		},
		PostgresqlCommits: MetricConfig{
			Enabled: true,
		},
		PostgresqlConnectionCount: MetricConfig{
			Enabled: true,
		},
		PostgresqlConnectionMax: MetricConfig{
			Enabled: true,
		},
		PostgresqlDatabaseCount: MetricConfig{
			Enabled: true,
		},
		PostgresqlDatabaseLocks: MetricConfig{
			Enabled: false,
		},
		PostgresqlDbSize: MetricConfig{
			Enabled: true,
		},
		PostgresqlDeadlocks: MetricConfig{
			Enabled: false,
		},
		PostgresqlFunctionCalls: MetricConfig{
			Enabled: false,
		},
		PostgresqlIndexBlocksRead: MetricConfig{
			Enabled: true,
		},
		PostgresqlIndexRowsRead: MetricConfig{
			Enabled: true,
		},
		PostgresqlIndexScans: MetricConfig{
			Enabled: true,
		},
		PostgresqlIndexSize: MetricConfig{
			Enabled: true,
		},
		PostgresqlIndexBloat: MetricConfig{
			Enabled: true,
		},
		PostgresqlLiveRows: MetricConfig{
			Enabled: true,
		},
		PostgresqlOperations: MetricConfig{
			Enabled: true,
		},
		PostgresqlQueryCount: MetricConfig{
			Enabled: true,
		},
		PostgresqlQueryTotalExecTime: MetricConfig{
			Enabled: true,
		},
		PostgresqlReplicationDataDelay: MetricConfig{
			Enabled: true,
		},
		PostgresqlRollbacks: MetricConfig{
			Enabled: true,
		},
		PostgresqlRows: MetricConfig{
			Enabled: true,
		},
		PostgresqlRowsDeleted: MetricConfig{
			Enabled: true,
		},
		PostgresqlRowsFetched: MetricConfig{
			Enabled: true,
		},
		PostgresqlRowsInserted: MetricConfig{
			Enabled: true,
		},
		PostgresqlRowsUpdated: MetricConfig{
			Enabled: true,
		},
		PostgresqlSequentialScans: MetricConfig{
			Enabled: false,
		},
		PostgresqlTableCount: MetricConfig{
			Enabled: true,
		},
		PostgresqlTableSize: MetricConfig{
			Enabled: true,
		},
		PostgresqlTableVacuumCount: MetricConfig{
			Enabled: true,
		},
		PostgresqlTableBloat: MetricConfig{
			Enabled: true,
		},
		PostgresqlTempIo: MetricConfig{
			Enabled: false,
		},
		PostgresqlTempFiles: MetricConfig{
			Enabled: false,
		},
		PostgresqlToastBlocksHit: MetricConfig{
			Enabled: true,
		},
		PostgresqlToastIndexBlocksRead: MetricConfig{
			Enabled: true,
		},
		PostgresqlToastSize: MetricConfig{
			Enabled: true,
		},
		PostgresqlTransactionsDurationMax: MetricConfig{
			Enabled: true,
		},
		PostgresqlTransactionsDurationSum: MetricConfig{
			Enabled: true,
		},
		PostgresqlTupDeleted: MetricConfig{
			Enabled: false,
		},
		PostgresqlTupFetched: MetricConfig{
			Enabled: false,
		},
		PostgresqlTupInserted: MetricConfig{
			Enabled: false,
		},
		PostgresqlTupReturned: MetricConfig{
			Enabled: false,
		},
		PostgresqlTupUpdated: MetricConfig{
			Enabled: false,
		},
		PostgresqlWalAge: MetricConfig{
			Enabled: true,
		},
		PostgresqlWalCount: MetricConfig{
			Enabled: true,
		},
		PostgresqlWalDelay: MetricConfig{
			Enabled: false,
		},
		PostgresqlWalLag: MetricConfig{
			Enabled: true,
		},
		PostgresqlWalSize: MetricConfig{
			Enabled: true,
		},
	}
}

// EventConfig provides common config for a particular event.
type EventConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ec *EventConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ec)
	if err != nil {
		return err
	}
	ec.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// EventsConfig provides config for postgresql events.
type EventsConfig struct {
	DbServerQuerySample EventConfig `mapstructure:"db.server.query_sample"`
	DbServerTopQuery    EventConfig `mapstructure:"db.server.top_query"`
}

func DefaultEventsConfig() EventsConfig {
	return EventsConfig{
		DbServerQuerySample: EventConfig{
			Enabled: true,
		},
		DbServerTopQuery: EventConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`
	// Experimental: EventsInclude defines a list of filters for attribute values.
	// If the list is not empty, only events with matching resource attribute values will be emitted.
	EventsInclude []filter.Config `mapstructure:"events_include"`
	// Experimental: EventsExclude defines a list of filters for attribute values.
	// If the list is not empty, events with matching resource attribute values will not be emitted.
	// EventsInclude has higher priority than EventsExclude.
	EventsExclude []filter.Config `mapstructure:"events_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for postgresql resource attributes.
type ResourceAttributesConfig struct {
	PostgresqlDatabaseName ResourceAttributeConfig `mapstructure:"postgresql.database.name"`
	PostgresqlDbVersion    ResourceAttributeConfig `mapstructure:"postgresql.db.version"`
	PostgresqlIndexName    ResourceAttributeConfig `mapstructure:"postgresql.index.name"`
	PostgresqlSchemaName   ResourceAttributeConfig `mapstructure:"postgresql.schema.name"`
	PostgresqlTableName    ResourceAttributeConfig `mapstructure:"postgresql.table.name"`
	ServiceInstanceID      ResourceAttributeConfig `mapstructure:"service.instance.id"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		PostgresqlDatabaseName: ResourceAttributeConfig{
			Enabled: true,
		},
		PostgresqlDbVersion: ResourceAttributeConfig{
			Enabled: true,
		},
		PostgresqlIndexName: ResourceAttributeConfig{
			Enabled: true,
		},
		PostgresqlSchemaName: ResourceAttributeConfig{
			Enabled: true,
		},
		PostgresqlTableName: ResourceAttributeConfig{
			Enabled: true,
		},
		ServiceInstanceID: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for postgresql metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}

// LogsBuilderConfig is a configuration for postgresql logs builder.
type LogsBuilderConfig struct {
	Events             EventsConfig             `mapstructure:"events"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultLogsBuilderConfig() LogsBuilderConfig {
	return LogsBuilderConfig{
		Events:             DefaultEventsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
