// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/k8s_cluster component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("k8s_cluster")
)

const (
	LogsStability    = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelBeta
)
