// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/kubelet_stats component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

var (
	Type           = component.MustNewType("kubelet_stats")
	DeprecatedType = component.MustNewType("kubeletstats")
	ScopeName      = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("otelcol/kubeletstatsreceiver")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("otelcol/kubeletstatsreceiver")
}
