// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/apache component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("apache")
)

const (
	MetricsStability = component.StabilityLevelBeta
)
